name: lolcats-env
channels:
  - conda-forge
  - pytorch
  - huggingface
  - nvidia
dependencies:
  - python>=3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8 # or 12.1 depending on your supported CUDA version
  - transformers=4.43.1 # Llama 3.1 support (updated RoPE)
  - datasets=2.15.0
  - nltk
  - rouge-score
  - sentencepiece
  - xopen
  - timm=0.4.12
  - numpy
  - pandas
  - einops
  - opt_einsum
  - jupyter
  - jupyterlab
  - matplotlib
  - omegaconf
  - tqdm
  - rich
  - wandb
  - pip:
    # - bitsandbytes>=0.39.0
      - peft==0.9.0
      - shortuuid
    # - openai  # for llm eval
    # - flash-attn  # --no-build-isolation
